/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t workspace_final.gltf 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type ActionName = "";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Bird: THREE.Mesh;
    Catdoll: THREE.Mesh;
    Desk: THREE.Mesh;
    Items: THREE.Mesh;
    Lamp_1: THREE.Mesh;
    Lamp_2: THREE.Mesh;
    PenHolder: THREE.Mesh;
    Rug_1: THREE.Mesh;
    Rug_2: THREE.Mesh;
  };
  materials: {
    BirdMaterial: THREE.MeshStandardMaterial;
    CatdollMaterial: THREE.MeshBasicMaterial;
    DeskMaterial: THREE.MeshStandardMaterial;
    ItemsMaterial: THREE.MeshStandardMaterial;
    ["LampLight.001"]: THREE.MeshStandardMaterial;
    ["LampMaterial.001"]: THREE.MeshStandardMaterial;
    PenHolderMaterial: THREE.MeshStandardMaterial;
    Contour: THREE.MeshStandardMaterial;
    RugMaterial: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Workspace(props: React.JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "models/workspace/bake/workspace_final.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Bird.geometry}
        material={materials.BirdMaterial}
        position={[0.027, 1.401, 0.594]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.Catdoll.geometry}
        material={materials.CatdollMaterial}
        position={[0.59, 0.339, -0.184]}
        rotation={[-0.123, 0.006, -0.052]}
        scale={0.022}
      />
      <mesh geometry={nodes.Desk.geometry} material={materials.DeskMaterial} />
      <mesh
        geometry={nodes.Items.geometry}
        material={materials.ItemsMaterial}
        position={[-0.137, 0.631, 0]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.893, 1.02, 1.02]}
      />
      <group position={[0, 0.02, 1.001]}>
        <mesh
          geometry={nodes.Lamp_1.geometry}
          material={materials["LampLight.001"]}
        />
        <mesh
          geometry={nodes.Lamp_2.geometry}
          material={materials["LampMaterial.001"]}
        />
      </group>
      <mesh
        geometry={nodes.PenHolder.geometry}
        material={materials.PenHolderMaterial}
        position={[-0.013, 0.634, 0.431]}
      />
      <group position={[0.923, 0, -0.137]}>
        <mesh geometry={nodes.Rug_1.geometry} material={materials.Contour} />
        <mesh
          geometry={nodes.Rug_2.geometry}
          material={materials.RugMaterial}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/workspace/bake/workspace_bake_final.glb");
